build: false
platform: x64

environment:
  global:
    PYTHONUNBUFFERED: "1"
    INSTALL_EDM_VERSION: "2.5.0"

  matrix:
    - CI_PYTHON_VERSION: "py36"
      CI_TOOLKIT: "null"
    - CI_PYTHON_VERSION: "py36"
      CI_TOOLKIT: "pyqt"
    - CI_PYTHON_VERSION: "py36"
      CI_TOOLKIT: "pyqt5"

cache:
  - C:\Users\appveyor\.cache -> appveyor-clean-cache.txt
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-clean-cache.txt

init:
  - ps: $Env:path = "C:/Enthought/edm;" + $Env:path
  - ps: md C:/Users/appveyor/.cache -Force

install:
  - install-edm-windows.cmd
  - edm install -y -e bootstrap click setuptools
  - edm run -e bootstrap -- python -m ci build ci

test_script:
  - edm run -e bootstrap -- python -m ci flake8
  - edm run -e bootstrap -- python -m ci test
