name: Check that documentation builds cleanly

on:
  pull_request

env:
  PYTHONUNBUFFERED: 1

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Install necessary apt-get packages
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install necessary Python packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Check out the PR branch
      uses: actions/checkout@v2
    - name: Install local package and documentation dependencies
      run: |
        python -m pip install .[doc]
    - name: Build HTML documentation
      run: |
        cd docs
        python -m sphinx -b html -d doctrees -W source build
