name: Check that documentation builds cleanly

on: [pull_request, workflow_dispatch]

env:
  PYTHONUNBUFFERED: 1

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Install necessary apt-get packages
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Check out the target commit
      uses: actions/checkout@v3
    - name: Install local package and documentation dependencies
      run: |
        python -m pip install -r docs/requirements.txt
        python -m pip install .
    - name: Build HTML documentation
      run: |
        cd docs
        python -m sphinx -b html -d doctrees -W source build
